#!/usr/bin/env python3
"""Apply reviewed license conclusions to a Syft SPDX JSON document."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Apply reviewed Community Edition conclusions to an SPDX JSON SBOM."
    )
    parser.add_argument("sbom", type=Path, help="Input SPDX JSON generated by Syft")
    parser.add_argument("output", type=Path, help="Output path for the reviewed SPDX JSON")
    parser.add_argument(
        "--conclusions",
        type=Path,
        default=Path("config/community/license-conclusions.json"),
        help="Reviewed conclusion manifest",
    )
    return parser.parse_args()


def package_key(package: dict[str, Any]) -> tuple[str, str]:
    return str(package.get("name", "")), str(package.get("versionInfo", ""))


def main() -> int:
    args = parse_args()
    sbom = json.loads(args.sbom.read_text(encoding="utf-8"))
    manifest = json.loads(args.conclusions.read_text(encoding="utf-8"))
    if manifest.get("schemaVersion") != 1:
        raise SystemExit("unsupported license conclusion schema")

    conclusions: dict[tuple[str, str], dict[str, str]] = {}
    for entry in manifest.get("entries", []):
        key = (str(entry.get("name", "")), str(entry.get("version", "")))
        if not key[0] or key in conclusions:
            raise SystemExit(f"invalid or duplicate license conclusion: {key!r}")
        if not entry.get("licenseConcluded") or not entry.get("evidence"):
            raise SystemExit(f"incomplete license conclusion: {key!r}")
        conclusions[key] = entry

    unresolved: list[tuple[str, str]] = []
    applied: set[tuple[str, str]] = set()
    for package in sbom.get("packages", []):
        if package.get("licenseConcluded") != "NOASSERTION":
            continue
        key = package_key(package)
        entry = conclusions.get(key)
        if entry is None:
            unresolved.append(key)
            continue
        package["licenseConcluded"] = entry["licenseConcluded"]
        if entry.get("licenseDeclared"):
            package["licenseDeclared"] = entry["licenseDeclared"]
        package["licenseComments"] = "Reviewed Community Edition conclusion: " + entry["evidence"]
        applied.add(key)

    if unresolved:
        rendered = "\n".join(f"- {name}@{version}" for name, version in unresolved)
        raise SystemExit(f"unresolved NOASSERTION packages:\n{rendered}")

    unused = sorted(set(conclusions) - applied)
    if unused:
        rendered = "\n".join(f"- {name}@{version}" for name, version in unused)
        raise SystemExit(f"reviewed conclusions not present in this SBOM:\n{rendered}")

    args.output.write_text(json.dumps(sbom, indent=2) + "\n", encoding="utf-8")
    print(f"applied {len(applied)} reviewed license conclusions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
