package base

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha512"
	"encoding/base64"
	"errors"
	"fmt"
	"io"
	"sync"
	"time"

	hd "github.com/btcsuite/btcd/btcutil/hdkeychain"
	"github.com/mobazha/mobazha3.0/internal/chains/database"
	iwallet "github.com/mobazha/mobazha3.0/pkg/wallet-interface"
	"golang.org/x/crypto/pbkdf2"
)

const (
	// defaultKdfRounds is the number of rounds to use when generating the
	// encryption key. The greater this number is, the harder it is to
	// brute force the encryption key.
	defaultKdfRounds = 8192

	// defaultKeyLength is the encryption key length generated by pbkdf2.
	defaultKeyLength = 32
)

// ErrEncryptedKeychain means the keychain is encrypted.
var ErrEncryptedKeychain = errors.New("keychain is encrypted")

// KeychainConfig holds some optional configuration options for
// the keychain.
type KeychainConfig struct {
	ExternalOnly bool
}

// Apply applies the given options to this Option
func (cfg *KeychainConfig) Apply(opts ...KeychainOption) error {
	for i, opt := range opts {
		if err := opt(cfg); err != nil {
			return fmt.Errorf("keychain option %d failed: %s", i, err)
		}
	}
	return nil
}

// KeychainOption is a keychain option type.
type KeychainOption func(*KeychainConfig) error

// Keychain manages a Bip44 keychain for each coin.
type Keychain struct {
	db              database.Database
	internalPrivkey *hd.ExtendedKey
	internalPubkey  *hd.ExtendedKey

	externalPrivkey *hd.ExtendedKey
	externalPubkey  *hd.ExtendedKey

	externalOnly bool

	coinType iwallet.CoinType

	mtx sync.RWMutex
}

// NewKeychain instantiates a new Keychain for the given coin with the provided keys.
//
// Note the following derivation path used by the Keychain:
// Typical Bip44 derivation is:
//
// m / purpose' / coin_type' / account' / change / address_index
//
// For our purpose we only store the `account` level so as to prevent this class from
// deriving keys for other coins. Further, we only generate addresses using the master
// public key keys so we do not need the master private key to generate new addresses.
// This allows us to encrypt the master private key if the user desires.
func NewKeychain(db database.Database, coinType iwallet.CoinType, opts ...KeychainOption) (*Keychain, error) {
	cfg := KeychainConfig{}
	if err := cfg.Apply(opts...); err != nil {
		return nil, err
	}
	var (
		externalPrivkey, externalPubkey, internalPrivkey, internalPubkey *hd.ExtendedKey
		coinRecord                                                       database.CoinRecord
	)
	err := db.View(func(tx database.Tx) error {
		return tx.Read().Where("coin=?", coinType.CurrencyCode()).Find(&coinRecord).Error
	})
	if err != nil {
		return nil, err
	}
	accountPubKey, err := hd.NewKeyFromString(coinRecord.MasterPub)
	if err != nil {
		return nil, err
	}
	externalPubkey, internalPubkey, err = generateAccountPubKeys(accountPubKey)
	if err != nil {
		return nil, err
	}

	if !coinRecord.EncryptedMasterKey {
		accountPrivKey, err := hd.NewKeyFromString(coinRecord.MasterPriv)
		if err != nil {
			return nil, err
		}
		externalPrivkey, internalPrivkey, err = generateAccountPrivKeys(accountPrivKey)
		if err != nil {
			return nil, err
		}
	}

	kc := &Keychain{
		db:                  db,
		internalPrivkey:     internalPrivkey,
		internalPubkey:      internalPubkey,
		externalPrivkey:     externalPrivkey,
		externalPubkey:      externalPubkey,
		externalOnly: cfg.ExternalOnly,
		coinType:            coinType,
		mtx:                 sync.RWMutex{},
	}
	return kc, nil
}

// SetPassphase encrypts the master private key in the database and
// deletes the internal and external private keys from memory.
func (kc *Keychain) SetPassphase(pw []byte) error {
	kc.mtx.Lock()
	defer kc.mtx.Unlock()

	var (
		salt       = make([]byte, 32)
		rounds     = defaultKdfRounds
		keyLen     = defaultKeyLength
		coinRecord database.CoinRecord
	)

	return kc.db.Update(func(tx database.Tx) error {
		err := tx.Read().Where("coin=?", kc.coinType.CurrencyCode()).Find(&coinRecord).Error
		if err != nil {
			return err
		}

		if coinRecord.EncryptedMasterKey {
			return errors.New("keychain already encrypted")
		}

		plaintext := []byte(coinRecord.MasterPriv)

		_, err = rand.Read(salt)
		if err != nil {
			return err
		}
		dk := pbkdf2.Key(pw, salt, rounds, keyLen, sha512.New)

		block, err := aes.NewCipher(dk)
		if err != nil {
			return err
		}

		// The IV needs to be unique, but not secure. Therefore it's common to
		// include it at the beginning of the ciphertext.
		ciphertext := make([]byte, aes.BlockSize+len(plaintext))
		iv := ciphertext[:aes.BlockSize]
		if _, err := io.ReadFull(rand.Reader, iv); err != nil {
			return err
		}

		stream := cipher.NewCFBEncrypter(block, iv)
		stream.XORKeyStream(ciphertext[aes.BlockSize:], plaintext)

		coinRecord.MasterPriv = base64.StdEncoding.EncodeToString(ciphertext)
		coinRecord.EncryptedMasterKey = true
		coinRecord.KdfRounds = rounds
		coinRecord.KdfKeyLen = keyLen
		coinRecord.Salt = salt

		kc.externalPrivkey = nil
		kc.internalPrivkey = nil

		return tx.Save(&coinRecord)
	})
}

// ChangePassphrase will change the passphrase used to encrypt the
// master private key.
func (kc *Keychain) ChangePassphrase(old, new []byte) error {
	kc.mtx.Lock()
	defer kc.mtx.Unlock()

	if kc.internalPrivkey != nil || kc.externalPrivkey != nil {
		return errors.New("wallet is not encrypted")
	}

	var (
		salt       = make([]byte, 32)
		rounds     = defaultKdfRounds
		keyLen     = defaultKeyLength
		coinRecord database.CoinRecord
	)

	return kc.db.Update(func(tx database.Tx) error {
		err := tx.Read().Where("coin=?", kc.coinType.CurrencyCode()).Find(&coinRecord).Error
		if err != nil {
			return err
		}

		ciphertext, err := base64.StdEncoding.DecodeString(coinRecord.MasterPriv)
		if err != nil {
			return err
		}

		dk := pbkdf2.Key(old, coinRecord.Salt, coinRecord.KdfRounds, coinRecord.KdfKeyLen, sha512.New)

		block, err := aes.NewCipher(dk)
		if err != nil {
			return err
		}

		// The IV needs to be unique, but not secure. Therefore it's common to
		// include it at the beginning of the ciphertext.
		if len(ciphertext) < aes.BlockSize {
			return errors.New("ciphertext too short")
		}
		iv := ciphertext[:aes.BlockSize]
		ciphertext = ciphertext[aes.BlockSize:]

		stream := cipher.NewCFBDecrypter(block, iv)

		// XORKeyStream can work in-place if the two arguments are the same.
		stream.XORKeyStream(ciphertext, ciphertext)

		plaintext := ciphertext

		_, err = hd.NewKeyFromString(string(plaintext))
		if err != nil {
			return errors.New("invalid passphrase")
		}

		_, err = rand.Read(salt)
		if err != nil {
			return err
		}

		dk = pbkdf2.Key(new, salt, rounds, keyLen, sha512.New)

		block, err = aes.NewCipher(dk)
		if err != nil {
			return err
		}

		// The IV needs to be unique, but not secure. Therefore it's common to
		// include it at the beginning of the ciphertext.
		ciphertext = make([]byte, aes.BlockSize+len(plaintext))
		iv = ciphertext[:aes.BlockSize]
		if _, err := io.ReadFull(rand.Reader, iv); err != nil {
			return err
		}

		stream = cipher.NewCFBEncrypter(block, iv)
		stream.XORKeyStream(ciphertext[aes.BlockSize:], plaintext)

		coinRecord.MasterPriv = base64.StdEncoding.EncodeToString(ciphertext)
		coinRecord.EncryptedMasterKey = true
		coinRecord.KdfRounds = rounds
		coinRecord.KdfKeyLen = keyLen
		coinRecord.Salt = salt

		return tx.Save(&coinRecord)
	})
}

// RemovePassphrase removes encryption from the master key and puts the
// external and internal keys back in memory.
func (kc *Keychain) RemovePassphrase(pw []byte) error {
	kc.mtx.Lock()
	defer kc.mtx.Unlock()

	if kc.internalPrivkey != nil || kc.externalPrivkey != nil {
		return errors.New("wallet is not encrypted")
	}

	return kc.db.Update(func(tx database.Tx) error {
		var coinRecord database.CoinRecord
		err := tx.Read().Where("coin=?", kc.coinType.CurrencyCode()).Find(&coinRecord).Error
		if err != nil {
			return err
		}

		ciphertext, err := base64.StdEncoding.DecodeString(coinRecord.MasterPriv)
		if err != nil {
			return err
		}

		dk := pbkdf2.Key(pw, coinRecord.Salt, coinRecord.KdfRounds, coinRecord.KdfKeyLen, sha512.New)

		block, err := aes.NewCipher(dk)
		if err != nil {
			return err
		}

		// The IV needs to be unique, but not secure. Therefore it's common to
		// include it at the beginning of the ciphertext.
		if len(ciphertext) < aes.BlockSize {
			return errors.New("ciphertext too short")
		}
		iv := ciphertext[:aes.BlockSize]
		ciphertext = ciphertext[aes.BlockSize:]

		stream := cipher.NewCFBDecrypter(block, iv)

		// XORKeyStream can work in-place if the two arguments are the same.
		stream.XORKeyStream(ciphertext, ciphertext)

		key, err := hd.NewKeyFromString(string(ciphertext))
		if err != nil {
			return errors.New("invalid passphrase")
		}

		kc.externalPrivkey, kc.internalPrivkey, err = generateAccountPrivKeys(key)
		if err != nil {
			return err
		}

		coinRecord.MasterPriv = string(ciphertext)
		coinRecord.EncryptedMasterKey = false

		return tx.Save(&coinRecord)
	})
}

// Unlock will dcrypt the master key and store the external and internal
// private keys in memory for howLong.
func (kc *Keychain) Unlock(pw []byte, howLong time.Duration) error {
	kc.mtx.Lock()
	defer kc.mtx.Unlock()

	if kc.internalPrivkey != nil || kc.externalPrivkey != nil {
		return errors.New("wallet is not encrypted")
	}

	var coinRecord database.CoinRecord
	err := kc.db.View(func(tx database.Tx) error {
		return tx.Read().Where("coin=?", kc.coinType.CurrencyCode()).Find(&coinRecord).Error
	})
	if err != nil {
		return err
	}

	ciphertext, err := base64.StdEncoding.DecodeString(coinRecord.MasterPriv)
	if err != nil {
		return err
	}

	dk := pbkdf2.Key(pw, coinRecord.Salt, coinRecord.KdfRounds, coinRecord.KdfKeyLen, sha512.New)

	block, err := aes.NewCipher(dk)
	if err != nil {
		return err
	}

	// The IV needs to be unique, but not secure. Therefore it's common to
	// include it at the beginning of the ciphertext.
	if len(ciphertext) < aes.BlockSize {
		return errors.New("ciphertext too short")
	}
	iv := ciphertext[:aes.BlockSize]
	ciphertext = ciphertext[aes.BlockSize:]

	stream := cipher.NewCFBDecrypter(block, iv)

	// XORKeyStream can work in-place if the two arguments are the same.
	stream.XORKeyStream(ciphertext, ciphertext)

	key, err := hd.NewKeyFromString(string(ciphertext))
	if err != nil {
		return err
	}

	kc.externalPrivkey, kc.internalPrivkey, err = generateAccountPrivKeys(key)
	if err != nil {
		return err
	}

	time.AfterFunc(howLong, func() {
		kc.mtx.Lock()
		defer kc.mtx.Unlock()

		kc.externalPrivkey = nil
		kc.internalPrivkey = nil
	})
	return nil
}

// IsEncrypted returns whether or not this keychain is encrypted.
func (kc *Keychain) IsEncrypted() bool {
	kc.mtx.RLock()
	defer kc.mtx.RUnlock()

	return kc.internalPrivkey == nil || kc.externalPrivkey == nil
}


func generateAccountPrivKeys(accountPrivKey *hd.ExtendedKey) (external, internal *hd.ExtendedKey, err error) {
	// Change(0) = external
	external, err = accountPrivKey.Derive(0)
	if err != nil {
		return nil, nil, err
	}
	// Change(1) = internal
	internal, err = accountPrivKey.Derive(1)
	if err != nil {
		return nil, nil, err
	}
	return
}

func generateAccountPubKeys(accountPubKey *hd.ExtendedKey) (external, internal *hd.ExtendedKey, err error) {
	// Change(0) = external
	external, err = accountPubKey.Derive(0)
	if err != nil {
		return nil, nil, err
	}
	// Change(1) = internal
	internal, err = accountPubKey.Derive(1)
	if err != nil {
		return nil, nil, err
	}
	return
}
