// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: common.proto

package mbzpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Divisibility  uint32                 `protobuf:"varint,2,opt,name=divisibility,proto3" json:"divisibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetDivisibility() uint32 {
	if x != nil {
		return x.Divisibility
	}
	return 0
}

type CurrencyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyValue) Reset() {
	*x = CurrencyValue{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyValue) ProtoMessage() {}

func (x *CurrencyValue) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyValue.ProtoReflect.Descriptor instead.
func (*CurrencyValue) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *CurrencyValue) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *CurrencyValue) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type ID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeerID        string                 `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Handle        string                 `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Pubkeys       *ID_Pubkeys            `protobuf:"bytes,3,opt,name=pubkeys,proto3" json:"pubkeys,omitempty"`
	Sig           []byte                 `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"` // secp256k1 signature covering peerID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID) Reset() {
	*x = ID{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *ID) GetPeerID() string {
	if x != nil {
		return x.PeerID
	}
	return ""
}

func (x *ID) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *ID) GetPubkeys() *ID_Pubkeys {
	if x != nil {
		return x.Pubkeys
	}
	return nil
}

func (x *ID) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Original      string                 `protobuf:"bytes,2,opt,name=original,proto3" json:"original,omitempty"`
	Large         string                 `protobuf:"bytes,3,opt,name=large,proto3" json:"large,omitempty"`
	Medium        string                 `protobuf:"bytes,4,opt,name=medium,proto3" json:"medium,omitempty"`
	Small         string                 `protobuf:"bytes,5,opt,name=small,proto3" json:"small,omitempty"`
	Tiny          string                 `protobuf:"bytes,6,opt,name=tiny,proto3" json:"tiny,omitempty"`
	Alt           string                 `protobuf:"bytes,7,opt,name=alt,proto3" json:"alt,omitempty"` // Alt text for accessibility and SEO
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Image) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Image) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *Image) GetLarge() string {
	if x != nil {
		return x.Large
	}
	return ""
}

func (x *Image) GetMedium() string {
	if x != nil {
		return x.Medium
	}
	return ""
}

func (x *Image) GetSmall() string {
	if x != nil {
		return x.Small
	}
	return ""
}

func (x *Image) GetTiny() string {
	if x != nil {
		return x.Tiny
	}
	return ""
}

func (x *Image) GetAlt() string {
	if x != nil {
		return x.Alt
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Filename      string                 `protobuf:"bytes,3,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *File) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *File) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type EscrowSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputIndex    uint32                 `protobuf:"varint,1,opt,name=inputIndex,proto3" json:"inputIndex,omitempty"`
	Sig           []byte                 `protobuf:"bytes,2,opt,name=sig,proto3" json:"sig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EscrowSignature) Reset() {
	*x = EscrowSignature{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EscrowSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EscrowSignature) ProtoMessage() {}

func (x *EscrowSignature) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EscrowSignature.ProtoReflect.Descriptor instead.
func (*EscrowSignature) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *EscrowSignature) GetInputIndex() uint32 {
	if x != nil {
		return x.InputIndex
	}
	return 0
}

func (x *EscrowSignature) GetSig() []byte {
	if x != nil {
		return x.Sig
	}
	return nil
}

type ID_Pubkeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identity      []byte                 `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"` // IPFS public key
	Escrow        []byte                 `protobuf:"bytes,2,opt,name=escrow,proto3" json:"escrow,omitempty"`     // Cryptocurrency escrow public key (BTC category)
	Eth           []byte                 `protobuf:"bytes,3,opt,name=eth,proto3" json:"eth,omitempty"`           // Cryptocurrency eth public key
	Solana        []byte                 `protobuf:"bytes,4,opt,name=solana,proto3" json:"solana,omitempty"`     // Solana public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ID_Pubkeys) Reset() {
	*x = ID_Pubkeys{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ID_Pubkeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID_Pubkeys) ProtoMessage() {}

func (x *ID_Pubkeys) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID_Pubkeys.ProtoReflect.Descriptor instead.
func (*ID_Pubkeys) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ID_Pubkeys) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ID_Pubkeys) GetEscrow() []byte {
	if x != nil {
		return x.Escrow
	}
	return nil
}

func (x *ID_Pubkeys) GetEth() []byte {
	if x != nil {
		return x.Eth
	}
	return nil
}

func (x *ID_Pubkeys) GetSolana() []byte {
	if x != nil {
		return x.Solana
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x05mbzpb\"B\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\"\n" +
	"\fdivisibility\x18\x02 \x01(\rR\fdivisibility\"T\n" +
	"\rCurrencyValue\x12+\n" +
	"\bcurrency\x18\x01 \x01(\v2\x0f.mbzpb.CurrencyR\bcurrency\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\"\xdc\x01\n" +
	"\x02ID\x12\x16\n" +
	"\x06peerID\x18\x01 \x01(\tR\x06peerID\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x12+\n" +
	"\apubkeys\x18\x03 \x01(\v2\x11.mbzpb.ID.PubkeysR\apubkeys\x12\x10\n" +
	"\x03sig\x18\x04 \x01(\fR\x03sig\x1ag\n" +
	"\aPubkeys\x12\x1a\n" +
	"\bidentity\x18\x01 \x01(\fR\bidentity\x12\x16\n" +
	"\x06escrow\x18\x02 \x01(\fR\x06escrow\x12\x10\n" +
	"\x03eth\x18\x03 \x01(\fR\x03eth\x12\x16\n" +
	"\x06solana\x18\x04 \x01(\fR\x06solana\"\xa9\x01\n" +
	"\x05Image\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1a\n" +
	"\boriginal\x18\x02 \x01(\tR\boriginal\x12\x14\n" +
	"\x05large\x18\x03 \x01(\tR\x05large\x12\x16\n" +
	"\x06medium\x18\x04 \x01(\tR\x06medium\x12\x14\n" +
	"\x05small\x18\x05 \x01(\tR\x05small\x12\x12\n" +
	"\x04tiny\x18\x06 \x01(\tR\x04tiny\x12\x10\n" +
	"\x03alt\x18\a \x01(\tR\x03alt\"J\n" +
	"\x04File\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\"C\n" +
	"\x0fEscrowSignature\x12\x1e\n" +
	"\n" +
	"inputIndex\x18\x01 \x01(\rR\n" +
	"inputIndex\x12\x10\n" +
	"\x03sig\x18\x02 \x01(\fR\x03sigB\n" +
	"Z\b../mbzpbb\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_proto_goTypes = []any{
	(*Currency)(nil),        // 0: mbzpb.Currency
	(*CurrencyValue)(nil),   // 1: mbzpb.CurrencyValue
	(*ID)(nil),              // 2: mbzpb.ID
	(*Image)(nil),           // 3: mbzpb.Image
	(*File)(nil),            // 4: mbzpb.File
	(*EscrowSignature)(nil), // 5: mbzpb.EscrowSignature
	(*ID_Pubkeys)(nil),      // 6: mbzpb.ID.Pubkeys
}
var file_common_proto_depIdxs = []int32{
	0, // 0: mbzpb.CurrencyValue.currency:type_name -> mbzpb.Currency
	6, // 1: mbzpb.ID.pubkeys:type_name -> mbzpb.ID.Pubkeys
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
