// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.5
// source: listing.proto

package mbzpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Listing_Metadata_ContractType int32

const (
	Listing_Metadata_PHYSICAL_GOOD  Listing_Metadata_ContractType = 0
	Listing_Metadata_DIGITAL_GOOD   Listing_Metadata_ContractType = 1
	Listing_Metadata_SERVICE        Listing_Metadata_ContractType = 2
	Listing_Metadata_CLASSIFIED     Listing_Metadata_ContractType = 3
	Listing_Metadata_CRYPTOCURRENCY Listing_Metadata_ContractType = 4
	Listing_Metadata_RWA_TOKEN      Listing_Metadata_ContractType = 5
)

// Enum value maps for Listing_Metadata_ContractType.
var (
	Listing_Metadata_ContractType_name = map[int32]string{
		0: "PHYSICAL_GOOD",
		1: "DIGITAL_GOOD",
		2: "SERVICE",
		3: "CLASSIFIED",
		4: "CRYPTOCURRENCY",
		5: "RWA_TOKEN",
	}
	Listing_Metadata_ContractType_value = map[string]int32{
		"PHYSICAL_GOOD":  0,
		"DIGITAL_GOOD":   1,
		"SERVICE":        2,
		"CLASSIFIED":     3,
		"CRYPTOCURRENCY": 4,
		"RWA_TOKEN":      5,
	}
)

func (x Listing_Metadata_ContractType) Enum() *Listing_Metadata_ContractType {
	p := new(Listing_Metadata_ContractType)
	*p = x
	return p
}

func (x Listing_Metadata_ContractType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Listing_Metadata_ContractType) Descriptor() protoreflect.EnumDescriptor {
	return file_listing_proto_enumTypes[0].Descriptor()
}

func (Listing_Metadata_ContractType) Type() protoreflect.EnumType {
	return &file_listing_proto_enumTypes[0]
}

func (x Listing_Metadata_ContractType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Listing_Metadata_ContractType.Descriptor instead.
func (Listing_Metadata_ContractType) EnumDescriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 0, 0}
}

type Listing_Metadata_Format int32

const (
	Listing_Metadata_FIXED_PRICE  Listing_Metadata_Format = 0
	Listing_Metadata_MARKET_PRICE Listing_Metadata_Format = 1
)

// Enum value maps for Listing_Metadata_Format.
var (
	Listing_Metadata_Format_name = map[int32]string{
		0: "FIXED_PRICE",
		1: "MARKET_PRICE",
	}
	Listing_Metadata_Format_value = map[string]int32{
		"FIXED_PRICE":  0,
		"MARKET_PRICE": 1,
	}
)

func (x Listing_Metadata_Format) Enum() *Listing_Metadata_Format {
	p := new(Listing_Metadata_Format)
	*p = x
	return p
}

func (x Listing_Metadata_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Listing_Metadata_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_listing_proto_enumTypes[1].Descriptor()
}

func (Listing_Metadata_Format) Type() protoreflect.EnumType {
	return &file_listing_proto_enumTypes[1]
}

func (x Listing_Metadata_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Listing_Metadata_Format.Descriptor instead.
func (Listing_Metadata_Format) EnumDescriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 0, 1}
}

type Listing_Metadata_RwaTradeMode int32

const (
	Listing_Metadata_RWA_TRADE_MODE_INSTANT          Listing_Metadata_RwaTradeMode = 0 // 即时交易（默认）
	Listing_Metadata_RWA_TRADE_MODE_CONFIRM_REQUIRED Listing_Metadata_RwaTradeMode = 1 // 需要确认
)

// Enum value maps for Listing_Metadata_RwaTradeMode.
var (
	Listing_Metadata_RwaTradeMode_name = map[int32]string{
		0: "RWA_TRADE_MODE_INSTANT",
		1: "RWA_TRADE_MODE_CONFIRM_REQUIRED",
	}
	Listing_Metadata_RwaTradeMode_value = map[string]int32{
		"RWA_TRADE_MODE_INSTANT":          0,
		"RWA_TRADE_MODE_CONFIRM_REQUIRED": 1,
	}
)

func (x Listing_Metadata_RwaTradeMode) Enum() *Listing_Metadata_RwaTradeMode {
	p := new(Listing_Metadata_RwaTradeMode)
	*p = x
	return p
}

func (x Listing_Metadata_RwaTradeMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Listing_Metadata_RwaTradeMode) Descriptor() protoreflect.EnumDescriptor {
	return file_listing_proto_enumTypes[2].Descriptor()
}

func (Listing_Metadata_RwaTradeMode) Type() protoreflect.EnumType {
	return &file_listing_proto_enumTypes[2]
}

func (x Listing_Metadata_RwaTradeMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Listing_Metadata_RwaTradeMode.Descriptor instead.
func (Listing_Metadata_RwaTradeMode) EnumDescriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 0, 2}
}

type ShippingRate_RateCondition_ConditionType int32

const (
	ShippingRate_RateCondition_NONE   ShippingRate_RateCondition_ConditionType = 0 // 无条件
	ShippingRate_RateCondition_WEIGHT ShippingRate_RateCondition_ConditionType = 1 // 基于重量
	ShippingRate_RateCondition_PRICE  ShippingRate_RateCondition_ConditionType = 2 // 基于价格
)

// Enum value maps for ShippingRate_RateCondition_ConditionType.
var (
	ShippingRate_RateCondition_ConditionType_name = map[int32]string{
		0: "NONE",
		1: "WEIGHT",
		2: "PRICE",
	}
	ShippingRate_RateCondition_ConditionType_value = map[string]int32{
		"NONE":   0,
		"WEIGHT": 1,
		"PRICE":  2,
	}
)

func (x ShippingRate_RateCondition_ConditionType) Enum() *ShippingRate_RateCondition_ConditionType {
	p := new(ShippingRate_RateCondition_ConditionType)
	*p = x
	return p
}

func (x ShippingRate_RateCondition_ConditionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShippingRate_RateCondition_ConditionType) Descriptor() protoreflect.EnumDescriptor {
	return file_listing_proto_enumTypes[3].Descriptor()
}

func (ShippingRate_RateCondition_ConditionType) Type() protoreflect.EnumType {
	return &file_listing_proto_enumTypes[3]
}

func (x ShippingRate_RateCondition_ConditionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShippingRate_RateCondition_ConditionType.Descriptor instead.
func (ShippingRate_RateCondition_ConditionType) EnumDescriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{2, 0, 0}
}

type Listing struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Slug              string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	VendorID          *ID                    `protobuf:"bytes,2,opt,name=vendorID,proto3" json:"vendorID,omitempty"`
	Metadata          *Listing_Metadata      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Item              *Listing_Item          `protobuf:"bytes,4,opt,name=item,proto3" json:"item,omitempty"`
	Taxes             []*Listing_Tax         `protobuf:"bytes,6,rep,name=taxes,proto3" json:"taxes,omitempty"`
	Moderators        []string               `protobuf:"bytes,8,rep,name=moderators,proto3" json:"moderators,omitempty"`
	Status            string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"` // "draft", "published", "private". Default is "published".
	Featured          bool                   `protobuf:"varint,12,opt,name=featured,proto3" json:"featured,omitempty"`
	ShippingProfile   *ShippingProfile       `protobuf:"bytes,13,opt,name=shippingProfile,proto3" json:"shippingProfile,omitempty"`     // P2P/IPFS 发布时嵌入的配送档案快照
	ShippingProfileId string                 `protobuf:"bytes,14,opt,name=shippingProfileId,proto3" json:"shippingProfileId,omitempty"` // 内部引用的配送档案 ID，发布时由后端解析为快照
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_listing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Listing) GetVendorID() *ID {
	if x != nil {
		return x.VendorID
	}
	return nil
}

func (x *Listing) GetMetadata() *Listing_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Listing) GetItem() *Listing_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *Listing) GetTaxes() []*Listing_Tax {
	if x != nil {
		return x.Taxes
	}
	return nil
}

func (x *Listing) GetModerators() []string {
	if x != nil {
		return x.Moderators
	}
	return nil
}

func (x *Listing) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Listing) GetFeatured() bool {
	if x != nil {
		return x.Featured
	}
	return false
}

func (x *Listing) GetShippingProfile() *ShippingProfile {
	if x != nil {
		return x.ShippingProfile
	}
	return nil
}

func (x *Listing) GetShippingProfileId() string {
	if x != nil {
		return x.ShippingProfileId
	}
	return ""
}

type SignedListing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listing       *Listing               `protobuf:"bytes,1,opt,name=listing,proto3" json:"listing,omitempty"`
	Cid           string                 `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedListing) Reset() {
	*x = SignedListing{}
	mi := &file_listing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedListing) ProtoMessage() {}

func (x *SignedListing) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedListing.ProtoReflect.Descriptor instead.
func (*SignedListing) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{1}
}

func (x *SignedListing) GetListing() *Listing {
	if x != nil {
		return x.Listing
	}
	return nil
}

func (x *SignedListing) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *SignedListing) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// ShippingRate 配送费率
type ShippingRate struct {
	state                 protoimpl.MessageState              `protogen:"open.v1"`
	Id                    string                              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                       // 费率 ID
	Name                  string                              `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                   // 费率名称（如 "标准配送"、"快递"）
	Price                 string                              `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`                                 // 价格（最小单位字符串）
	Currency              string                              `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                           // 货币代码
	EstimatedDelivery     string                              `protobuf:"bytes,5,opt,name=estimatedDelivery,proto3" json:"estimatedDelivery,omitempty"`         // 预计送达时间（如 "5-7 天"）
	Condition             *ShippingRate_RateCondition         `protobuf:"bytes,6,opt,name=condition,proto3" json:"condition,omitempty"`                         // 可选条件（基于重量或价格）
	FreeShippingThreshold *ShippingRate_FreeShippingThreshold `protobuf:"bytes,7,opt,name=freeShippingThreshold,proto3" json:"freeShippingThreshold,omitempty"` // 满额免邮配置
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ShippingRate) Reset() {
	*x = ShippingRate{}
	mi := &file_listing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingRate) ProtoMessage() {}

func (x *ShippingRate) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingRate.ProtoReflect.Descriptor instead.
func (*ShippingRate) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{2}
}

func (x *ShippingRate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShippingRate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShippingRate) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *ShippingRate) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ShippingRate) GetEstimatedDelivery() string {
	if x != nil {
		return x.EstimatedDelivery
	}
	return ""
}

func (x *ShippingRate) GetCondition() *ShippingRate_RateCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *ShippingRate) GetFreeShippingThreshold() *ShippingRate_FreeShippingThreshold {
	if x != nil {
		return x.FreeShippingThreshold
	}
	return nil
}

// ShippingZone 配送区域
type ShippingZone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // 区域 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // 区域名称（如 "全球"、"亚洲"、"北美"）
	Regions       []string               `protobuf:"bytes,3,rep,name=regions,proto3" json:"regions,omitempty"` // 配送区域（ISO 3166-1 alpha-2 代码，如 "CN", "US"，或 "ALL"）
	Rates         []*ShippingRate        `protobuf:"bytes,4,rep,name=rates,proto3" json:"rates,omitempty"`     // 该区域的费率列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingZone) Reset() {
	*x = ShippingZone{}
	mi := &file_listing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingZone) ProtoMessage() {}

func (x *ShippingZone) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingZone.ProtoReflect.Descriptor instead.
func (*ShippingZone) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{3}
}

func (x *ShippingZone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShippingZone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShippingZone) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *ShippingZone) GetRates() []*ShippingRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

// ShippingLocation 发货地点
type ShippingLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                // 地点 ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`            // 地点名称（如 "北京仓"、"美国仓"）
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`      // 地址（可选）
	IsDefault     bool                   `protobuf:"varint,4,opt,name=isDefault,proto3" json:"isDefault,omitempty"` // 是否为默认地点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingLocation) Reset() {
	*x = ShippingLocation{}
	mi := &file_listing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingLocation) ProtoMessage() {}

func (x *ShippingLocation) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingLocation.ProtoReflect.Descriptor instead.
func (*ShippingLocation) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{4}
}

func (x *ShippingLocation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShippingLocation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShippingLocation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ShippingLocation) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

// LocationGroup 发货地点组
// locationIds 留空表示适用于所有发货地点（默认行为）
type LocationGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // 地点组 ID
	LocationIds   []string               `protobuf:"bytes,2,rep,name=locationIds,proto3" json:"locationIds,omitempty"` // 关联的发货地点 ID 列表（留空 = 全局适用）
	Zones         []*ShippingZone        `protobuf:"bytes,3,rep,name=zones,proto3" json:"zones,omitempty"`             // 该地点组的配送区域
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationGroup) Reset() {
	*x = LocationGroup{}
	mi := &file_listing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationGroup) ProtoMessage() {}

func (x *LocationGroup) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationGroup.ProtoReflect.Descriptor instead.
func (*LocationGroup) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{5}
}

func (x *LocationGroup) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LocationGroup) GetLocationIds() []string {
	if x != nil {
		return x.LocationIds
	}
	return nil
}

func (x *LocationGroup) GetZones() []*ShippingZone {
	if x != nil {
		return x.Zones
	}
	return nil
}

// ShippingProfile 配送档案（Shopify 风格）
// 始终使用 locationGroups，每个 LocationGroup 包含独立的配送区域
// 单仓库卖家自动创建一个默认 LocationGroup（locationIds 留空）
type ShippingProfile struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProfileID      string                 `protobuf:"bytes,1,opt,name=profileID,proto3" json:"profileID,omitempty"`           // UUID，唯一标识
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                     // 档案名称：如"默认配送"、"易碎品配送"
	IsDefault      bool                   `protobuf:"varint,3,opt,name=isDefault,proto3" json:"isDefault,omitempty"`          // 是否为默认档案
	LocationGroups []*LocationGroup       `protobuf:"bytes,4,rep,name=locationGroups,proto3" json:"locationGroups,omitempty"` // 发货地点组列表（至少一个）
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`           // 创建时间
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`           // 更新时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShippingProfile) Reset() {
	*x = ShippingProfile{}
	mi := &file_listing_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingProfile) ProtoMessage() {}

func (x *ShippingProfile) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingProfile.ProtoReflect.Descriptor instead.
func (*ShippingProfile) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{6}
}

func (x *ShippingProfile) GetProfileID() string {
	if x != nil {
		return x.ProfileID
	}
	return ""
}

func (x *ShippingProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ShippingProfile) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *ShippingProfile) GetLocationGroups() []*LocationGroup {
	if x != nil {
		return x.LocationGroups
	}
	return nil
}

func (x *ShippingProfile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ShippingProfile) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Listing_Metadata struct {
	state                   protoimpl.MessageState        `protogen:"open.v1"`
	Version                 uint32                        `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ContractType            Listing_Metadata_ContractType `protobuf:"varint,2,opt,name=contractType,proto3,enum=mbzpb.Listing_Metadata_ContractType" json:"contractType,omitempty"`
	Format                  Listing_Metadata_Format       `protobuf:"varint,3,opt,name=format,proto3,enum=mbzpb.Listing_Metadata_Format" json:"format,omitempty"`
	Expiry                  *timestamppb.Timestamp        `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	AcceptedCurrencies      []string                      `protobuf:"bytes,5,rep,name=acceptedCurrencies,proto3" json:"acceptedCurrencies,omitempty"` // RWA/Crypto 商品接受的支付币种
	Language                string                        `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	EscrowTimeoutHours      uint32                        `protobuf:"varint,7,opt,name=escrowTimeoutHours,proto3" json:"escrowTimeoutHours,omitempty"`
	PricingCurrency         *Currency                     `protobuf:"bytes,9,opt,name=pricingCurrency,proto3" json:"pricingCurrency,omitempty"`
	RwaTradeMode            Listing_Metadata_RwaTradeMode `protobuf:"varint,10,opt,name=rwaTradeMode,proto3,enum=mbzpb.Listing_Metadata_RwaTradeMode" json:"rwaTradeMode,omitempty"` // RWA 交易模式
	RwaEscrowTimeoutSeconds uint64                        `protobuf:"varint,11,opt,name=rwaEscrowTimeoutSeconds,proto3" json:"rwaEscrowTimeoutSeconds,omitempty"`                    // RWA 托管超时时间（秒），默认86400（24小时）
	RwaListingId            uint64                        `protobuf:"varint,12,opt,name=rwaListingId,proto3" json:"rwaListingId,omitempty"`                                          // RWA 合约 Listing ID（延迟模式必填，用于 createOrderFromListing）
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Listing_Metadata) Reset() {
	*x = Listing_Metadata{}
	mi := &file_listing_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Metadata) ProtoMessage() {}

func (x *Listing_Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Metadata.ProtoReflect.Descriptor instead.
func (*Listing_Metadata) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Listing_Metadata) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Listing_Metadata) GetContractType() Listing_Metadata_ContractType {
	if x != nil {
		return x.ContractType
	}
	return Listing_Metadata_PHYSICAL_GOOD
}

func (x *Listing_Metadata) GetFormat() Listing_Metadata_Format {
	if x != nil {
		return x.Format
	}
	return Listing_Metadata_FIXED_PRICE
}

func (x *Listing_Metadata) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *Listing_Metadata) GetAcceptedCurrencies() []string {
	if x != nil {
		return x.AcceptedCurrencies
	}
	return nil
}

func (x *Listing_Metadata) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Listing_Metadata) GetEscrowTimeoutHours() uint32 {
	if x != nil {
		return x.EscrowTimeoutHours
	}
	return 0
}

func (x *Listing_Metadata) GetPricingCurrency() *Currency {
	if x != nil {
		return x.PricingCurrency
	}
	return nil
}

func (x *Listing_Metadata) GetRwaTradeMode() Listing_Metadata_RwaTradeMode {
	if x != nil {
		return x.RwaTradeMode
	}
	return Listing_Metadata_RWA_TRADE_MODE_INSTANT
}

func (x *Listing_Metadata) GetRwaEscrowTimeoutSeconds() uint64 {
	if x != nil {
		return x.RwaEscrowTimeoutSeconds
	}
	return 0
}

func (x *Listing_Metadata) GetRwaListingId() uint64 {
	if x != nil {
		return x.RwaListingId
	}
	return 0
}

type Listing_Item struct {
	state                      protoimpl.MessageState          `protogen:"open.v1"`
	Title                      string                          `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description                string                          `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ShortDescription           string                          `protobuf:"bytes,3,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	ProcessingTime             string                          `protobuf:"bytes,4,opt,name=processingTime,proto3" json:"processingTime,omitempty"`
	Nsfw                       bool                            `protobuf:"varint,5,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Tags                       []string                        `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Images                     []*Image                        `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	IntroVideo                 *File                           `protobuf:"bytes,8,opt,name=introVideo,proto3" json:"introVideo,omitempty"`
	ProductType                string                          `protobuf:"bytes,9,opt,name=productType,proto3" json:"productType,omitempty"`
	Grams                      uint32                          `protobuf:"varint,10,opt,name=grams,proto3" json:"grams,omitempty"`
	Dimensions                 *Listing_Item_Dimensions        `protobuf:"bytes,11,opt,name=dimensions,proto3" json:"dimensions,omitempty"`
	Condition                  string                          `protobuf:"bytes,12,opt,name=condition,proto3" json:"condition,omitempty"`
	Options                    []*Listing_Item_Option          `protobuf:"bytes,13,rep,name=options,proto3" json:"options,omitempty"`
	Skus                       []*Listing_Item_Sku             `protobuf:"bytes,14,rep,name=skus,proto3" json:"skus,omitempty"`
	Price                      string                          `protobuf:"bytes,15,opt,name=price,proto3" json:"price,omitempty"`
	RegularPrice               string                          `protobuf:"bytes,16,opt,name=regularPrice,proto3" json:"regularPrice,omitempty"`
	SalePrice                  string                          `protobuf:"bytes,17,opt,name=salePrice,proto3" json:"salePrice,omitempty"`
	OptionalFeatures           []*Listing_Item_OptionalFeature `protobuf:"bytes,18,rep,name=optionalFeatures,proto3" json:"optionalFeatures,omitempty"`
	CryptoListingCurrencyCode  string                          `protobuf:"bytes,19,opt,name=cryptoListingCurrencyCode,proto3" json:"cryptoListingCurrencyCode,omitempty"`
	CryptoListingPriceModifier float32                         `protobuf:"fixed32,20,opt,name=cryptoListingPriceModifier,proto3" json:"cryptoListingPriceModifier,omitempty"`
	AltIntroVideoLinks         []string                        `protobuf:"bytes,21,rep,name=altIntroVideoLinks,proto3" json:"altIntroVideoLinks,omitempty"`
	MinQuantity                string                          `protobuf:"bytes,22,opt,name=minQuantity,proto3" json:"minQuantity,omitempty"`
	MaxQuantity                string                          `protobuf:"bytes,23,opt,name=maxQuantity,proto3" json:"maxQuantity,omitempty"`
	Blockchain                 string                          `protobuf:"bytes,24,opt,name=blockchain,proto3" json:"blockchain,omitempty"`           // RWA Token 区块链 (ethereum, sepolia, bsc, solana等)
	TokenAddress               string                          `protobuf:"bytes,25,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`       // RWA Token 合约地址
	TokenStandard              string                          `protobuf:"bytes,26,opt,name=tokenStandard,proto3" json:"tokenStandard,omitempty"`     // Token 标准 (RWA, ERC20, ERC721, ERC1155, ERC3525, SPL等)
	TokenId                    string                          `protobuf:"bytes,27,opt,name=tokenId,proto3" json:"tokenId,omitempty"`                 // Token ID (ERC721/ERC1155/ERC3525 必填)
	SlotId                     string                          `protobuf:"bytes,28,opt,name=slotId,proto3" json:"slotId,omitempty"`                   // Slot ID (ERC3525 专用，表示资产类别/剧目)
	WeightUnit                 string                          `protobuf:"bytes,29,opt,name=weightUnit,proto3" json:"weightUnit,omitempty"`           // 重量单位: "g"(默认)/"kg"/"lb"/"oz"
	InventoryPolicy            string                          `protobuf:"bytes,30,opt,name=inventoryPolicy,proto3" json:"inventoryPolicy,omitempty"` // 库存策略: "deny"(默认)/"continue" - 缺货时是否继续销售
	PackageLength              float32                         `protobuf:"fixed32,31,opt,name=packageLength,proto3" json:"packageLength,omitempty"`   // 包裹长度
	PackageWidth               float32                         `protobuf:"fixed32,32,opt,name=packageWidth,proto3" json:"packageWidth,omitempty"`     // 包裹宽度
	PackageHeight              float32                         `protobuf:"fixed32,33,opt,name=packageHeight,proto3" json:"packageHeight,omitempty"`   // 包裹高度
	DimensionUnit              string                          `protobuf:"bytes,34,opt,name=dimensionUnit,proto3" json:"dimensionUnit,omitempty"`     // 尺寸单位: "cm"(默认)/"in"
	Brand                      string                          `protobuf:"bytes,35,opt,name=brand,proto3" json:"brand,omitempty"`                     // 品牌名称
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Listing_Item) Reset() {
	*x = Listing_Item{}
	mi := &file_listing_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item) ProtoMessage() {}

func (x *Listing_Item) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item.ProtoReflect.Descriptor instead.
func (*Listing_Item) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Listing_Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Listing_Item) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing_Item) GetShortDescription() string {
	if x != nil {
		return x.ShortDescription
	}
	return ""
}

func (x *Listing_Item) GetProcessingTime() string {
	if x != nil {
		return x.ProcessingTime
	}
	return ""
}

func (x *Listing_Item) GetNsfw() bool {
	if x != nil {
		return x.Nsfw
	}
	return false
}

func (x *Listing_Item) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Listing_Item) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Listing_Item) GetIntroVideo() *File {
	if x != nil {
		return x.IntroVideo
	}
	return nil
}

func (x *Listing_Item) GetProductType() string {
	if x != nil {
		return x.ProductType
	}
	return ""
}

func (x *Listing_Item) GetGrams() uint32 {
	if x != nil {
		return x.Grams
	}
	return 0
}

func (x *Listing_Item) GetDimensions() *Listing_Item_Dimensions {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Listing_Item) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Listing_Item) GetOptions() []*Listing_Item_Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Listing_Item) GetSkus() []*Listing_Item_Sku {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *Listing_Item) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Listing_Item) GetRegularPrice() string {
	if x != nil {
		return x.RegularPrice
	}
	return ""
}

func (x *Listing_Item) GetSalePrice() string {
	if x != nil {
		return x.SalePrice
	}
	return ""
}

func (x *Listing_Item) GetOptionalFeatures() []*Listing_Item_OptionalFeature {
	if x != nil {
		return x.OptionalFeatures
	}
	return nil
}

func (x *Listing_Item) GetCryptoListingCurrencyCode() string {
	if x != nil {
		return x.CryptoListingCurrencyCode
	}
	return ""
}

func (x *Listing_Item) GetCryptoListingPriceModifier() float32 {
	if x != nil {
		return x.CryptoListingPriceModifier
	}
	return 0
}

func (x *Listing_Item) GetAltIntroVideoLinks() []string {
	if x != nil {
		return x.AltIntroVideoLinks
	}
	return nil
}

func (x *Listing_Item) GetMinQuantity() string {
	if x != nil {
		return x.MinQuantity
	}
	return ""
}

func (x *Listing_Item) GetMaxQuantity() string {
	if x != nil {
		return x.MaxQuantity
	}
	return ""
}

func (x *Listing_Item) GetBlockchain() string {
	if x != nil {
		return x.Blockchain
	}
	return ""
}

func (x *Listing_Item) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *Listing_Item) GetTokenStandard() string {
	if x != nil {
		return x.TokenStandard
	}
	return ""
}

func (x *Listing_Item) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *Listing_Item) GetSlotId() string {
	if x != nil {
		return x.SlotId
	}
	return ""
}

func (x *Listing_Item) GetWeightUnit() string {
	if x != nil {
		return x.WeightUnit
	}
	return ""
}

func (x *Listing_Item) GetInventoryPolicy() string {
	if x != nil {
		return x.InventoryPolicy
	}
	return ""
}

func (x *Listing_Item) GetPackageLength() float32 {
	if x != nil {
		return x.PackageLength
	}
	return 0
}

func (x *Listing_Item) GetPackageWidth() float32 {
	if x != nil {
		return x.PackageWidth
	}
	return 0
}

func (x *Listing_Item) GetPackageHeight() float32 {
	if x != nil {
		return x.PackageHeight
	}
	return 0
}

func (x *Listing_Item) GetDimensionUnit() string {
	if x != nil {
		return x.DimensionUnit
	}
	return ""
}

func (x *Listing_Item) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

type Listing_Tax struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxType       string                 `protobuf:"bytes,1,opt,name=taxType,proto3" json:"taxType,omitempty"`
	TaxRegions    []string               `protobuf:"bytes,2,rep,name=taxRegions,proto3" json:"taxRegions,omitempty"` // ISO 3166-1 alpha-2 codes
	TaxShipping   bool                   `protobuf:"varint,3,opt,name=taxShipping,proto3" json:"taxShipping,omitempty"`
	Percentage    float32                `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing_Tax) Reset() {
	*x = Listing_Tax{}
	mi := &file_listing_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Tax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Tax) ProtoMessage() {}

func (x *Listing_Tax) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Tax.ProtoReflect.Descriptor instead.
func (*Listing_Tax) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Listing_Tax) GetTaxType() string {
	if x != nil {
		return x.TaxType
	}
	return ""
}

func (x *Listing_Tax) GetTaxRegions() []string {
	if x != nil {
		return x.TaxRegions
	}
	return nil
}

func (x *Listing_Tax) GetTaxShipping() bool {
	if x != nil {
		return x.TaxShipping
	}
	return false
}

func (x *Listing_Tax) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type Listing_Item_Option struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Name          string                         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                         `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Variants      []*Listing_Item_Option_Variant `protobuf:"bytes,3,rep,name=variants,proto3" json:"variants,omitempty"` // bool variation = 4; // 已移除：Shopify 模型中所有 option 均参与变体组合
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing_Item_Option) Reset() {
	*x = Listing_Item_Option{}
	mi := &file_listing_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Item_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Option) ProtoMessage() {}

func (x *Listing_Item_Option) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Option.ProtoReflect.Descriptor instead.
func (*Listing_Item_Option) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Listing_Item_Option) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listing_Item_Option) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Listing_Item_Option) GetVariants() []*Listing_Item_Option_Variant {
	if x != nil {
		return x.Variants
	}
	return nil
}

type Listing_Item_Sku struct {
	state          protoimpl.MessageState        `protogen:"open.v1"`
	Selections     []*Listing_Item_Sku_Selection `protobuf:"bytes,1,rep,name=selections,proto3" json:"selections,omitempty"`
	ProductID      string                        `protobuf:"bytes,2,opt,name=productID,proto3" json:"productID,omitempty"`
	Quantity       string                        `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price          string                        `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"` // 变体绝对价格（Shopify 风格，替代 surcharge）
	Images         []*Image                      `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Downloadable   bool                          `protobuf:"varint,6,opt,name=downloadable,proto3" json:"downloadable,omitempty"`
	Downloads      []*Listing_Item_Sku_Download  `protobuf:"bytes,7,rep,name=downloads,proto3" json:"downloads,omitempty"`
	CompareAtPrice string                        `protobuf:"bytes,8,opt,name=compareAtPrice,proto3" json:"compareAtPrice,omitempty"` // 划线价/原价（展示折扣用）
	Barcode        string                        `protobuf:"bytes,9,opt,name=barcode,proto3" json:"barcode,omitempty"`               // 条码（UPC/EAN/ISBN）
	Weight         uint32                        `protobuf:"varint,10,opt,name=weight,proto3" json:"weight,omitempty"`               // 变体重量（克），覆盖 Item.grams
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Listing_Item_Sku) Reset() {
	*x = Listing_Item_Sku{}
	mi := &file_listing_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Item_Sku) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Sku) ProtoMessage() {}

func (x *Listing_Item_Sku) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Sku.ProtoReflect.Descriptor instead.
func (*Listing_Item_Sku) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Listing_Item_Sku) GetSelections() []*Listing_Item_Sku_Selection {
	if x != nil {
		return x.Selections
	}
	return nil
}

func (x *Listing_Item_Sku) GetProductID() string {
	if x != nil {
		return x.ProductID
	}
	return ""
}

func (x *Listing_Item_Sku) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *Listing_Item_Sku) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Listing_Item_Sku) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Listing_Item_Sku) GetDownloadable() bool {
	if x != nil {
		return x.Downloadable
	}
	return false
}

func (x *Listing_Item_Sku) GetDownloads() []*Listing_Item_Sku_Download {
	if x != nil {
		return x.Downloads
	}
	return nil
}

func (x *Listing_Item_Sku) GetCompareAtPrice() string {
	if x != nil {
		return x.CompareAtPrice
	}
	return ""
}

func (x *Listing_Item_Sku) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Listing_Item_Sku) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type Listing_Item_Dimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        uint32                 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Width         uint32                 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing_Item_Dimensions) Reset() {
	*x = Listing_Item_Dimensions{}
	mi := &file_listing_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Item_Dimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Dimensions) ProtoMessage() {}

func (x *Listing_Item_Dimensions) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Dimensions.ProtoReflect.Descriptor instead.
func (*Listing_Item_Dimensions) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 2}
}

func (x *Listing_Item_Dimensions) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *Listing_Item_Dimensions) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Listing_Item_Dimensions) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Listing_Item_OptionalFeature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Surcharge     string                 `protobuf:"bytes,3,opt,name=surcharge,proto3" json:"surcharge,omitempty"`
	SkuID         string                 `protobuf:"bytes,4,opt,name=skuID,proto3" json:"skuID,omitempty"`
	Images        []*Image               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing_Item_OptionalFeature) Reset() {
	*x = Listing_Item_OptionalFeature{}
	mi := &file_listing_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Item_OptionalFeature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_OptionalFeature) ProtoMessage() {}

func (x *Listing_Item_OptionalFeature) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_OptionalFeature.ProtoReflect.Descriptor instead.
func (*Listing_Item_OptionalFeature) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 3}
}

func (x *Listing_Item_OptionalFeature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listing_Item_OptionalFeature) GetSurcharge() string {
	if x != nil {
		return x.Surcharge
	}
	return ""
}

func (x *Listing_Item_OptionalFeature) GetSkuID() string {
	if x != nil {
		return x.SkuID
	}
	return ""
}

func (x *Listing_Item_OptionalFeature) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Listing_Item_Option_Variant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         *Image                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing_Item_Option_Variant) Reset() {
	*x = Listing_Item_Option_Variant{}
	mi := &file_listing_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Item_Option_Variant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Option_Variant) ProtoMessage() {}

func (x *Listing_Item_Option_Variant) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Option_Variant.ProtoReflect.Descriptor instead.
func (*Listing_Item_Option_Variant) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 0, 0}
}

func (x *Listing_Item_Option_Variant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listing_Item_Option_Variant) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

type Listing_Item_Sku_Selection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        string                 `protobuf:"bytes,1,opt,name=option,proto3" json:"option,omitempty"`
	Variant       string                 `protobuf:"bytes,2,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing_Item_Sku_Selection) Reset() {
	*x = Listing_Item_Sku_Selection{}
	mi := &file_listing_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Item_Sku_Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Sku_Selection) ProtoMessage() {}

func (x *Listing_Item_Sku_Selection) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Sku_Selection.ProtoReflect.Descriptor instead.
func (*Listing_Item_Sku_Selection) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 1, 0}
}

func (x *Listing_Item_Sku_Selection) GetOption() string {
	if x != nil {
		return x.Option
	}
	return ""
}

func (x *Listing_Item_Sku_Selection) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type Listing_Item_Sku_Download struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DownloadID    string                 `protobuf:"bytes,1,opt,name=downloadID,proto3" json:"downloadID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing_Item_Sku_Download) Reset() {
	*x = Listing_Item_Sku_Download{}
	mi := &file_listing_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing_Item_Sku_Download) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing_Item_Sku_Download) ProtoMessage() {}

func (x *Listing_Item_Sku_Download) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing_Item_Sku_Download.ProtoReflect.Descriptor instead.
func (*Listing_Item_Sku_Download) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{0, 1, 1, 1}
}

func (x *Listing_Item_Sku_Download) GetDownloadID() string {
	if x != nil {
		return x.DownloadID
	}
	return ""
}

func (x *Listing_Item_Sku_Download) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Listing_Item_Sku_Download) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

// 费率条件
type ShippingRate_RateCondition struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Type          ShippingRate_RateCondition_ConditionType `protobuf:"varint,1,opt,name=type,proto3,enum=mbzpb.ShippingRate_RateCondition_ConditionType" json:"type,omitempty"` // 条件类型
	MinValue      uint32                                   `protobuf:"varint,2,opt,name=minValue,proto3" json:"minValue,omitempty"`                                             // 最小值（重量为克，价格为最小单位）
	MaxValue      uint32                                   `protobuf:"varint,3,opt,name=maxValue,proto3" json:"maxValue,omitempty"`                                             // 最大值（0 表示无上限）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingRate_RateCondition) Reset() {
	*x = ShippingRate_RateCondition{}
	mi := &file_listing_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingRate_RateCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingRate_RateCondition) ProtoMessage() {}

func (x *ShippingRate_RateCondition) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingRate_RateCondition.ProtoReflect.Descriptor instead.
func (*ShippingRate_RateCondition) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ShippingRate_RateCondition) GetType() ShippingRate_RateCondition_ConditionType {
	if x != nil {
		return x.Type
	}
	return ShippingRate_RateCondition_NONE
}

func (x *ShippingRate_RateCondition) GetMinValue() uint32 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *ShippingRate_RateCondition) GetMaxValue() uint32 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

// 满额免邮配置
type ShippingRate_FreeShippingThreshold struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`    // 是否启用满额免邮
	MinAmount     string                 `protobuf:"bytes,2,opt,name=minAmount,proto3" json:"minAmount,omitempty"` // 最低金额（最小单位）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingRate_FreeShippingThreshold) Reset() {
	*x = ShippingRate_FreeShippingThreshold{}
	mi := &file_listing_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingRate_FreeShippingThreshold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingRate_FreeShippingThreshold) ProtoMessage() {}

func (x *ShippingRate_FreeShippingThreshold) ProtoReflect() protoreflect.Message {
	mi := &file_listing_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingRate_FreeShippingThreshold.ProtoReflect.Descriptor instead.
func (*ShippingRate_FreeShippingThreshold) Descriptor() ([]byte, []int) {
	return file_listing_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ShippingRate_FreeShippingThreshold) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShippingRate_FreeShippingThreshold) GetMinAmount() string {
	if x != nil {
		return x.MinAmount
	}
	return ""
}

var File_listing_proto protoreflect.FileDescriptor

const file_listing_proto_rawDesc = "" +
	"\n" +
	"\rlisting.proto\x12\x05mbzpb\x1a\fcommon.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x1c\n" +
	"\aListing\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12%\n" +
	"\bvendorID\x18\x02 \x01(\v2\t.mbzpb.IDR\bvendorID\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.mbzpb.Listing.MetadataR\bmetadata\x12'\n" +
	"\x04item\x18\x04 \x01(\v2\x13.mbzpb.Listing.ItemR\x04item\x12(\n" +
	"\x05taxes\x18\x06 \x03(\v2\x12.mbzpb.Listing.TaxR\x05taxes\x12\x1e\n" +
	"\n" +
	"moderators\x18\b \x03(\tR\n" +
	"moderators\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1a\n" +
	"\bfeatured\x18\f \x01(\bR\bfeatured\x12@\n" +
	"\x0fshippingProfile\x18\r \x01(\v2\x16.mbzpb.ShippingProfileR\x0fshippingProfile\x12,\n" +
	"\x11shippingProfileId\x18\x0e \x01(\tR\x11shippingProfileId\x1a\xac\x06\n" +
	"\bMetadata\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12H\n" +
	"\fcontractType\x18\x02 \x01(\x0e2$.mbzpb.Listing.Metadata.ContractTypeR\fcontractType\x126\n" +
	"\x06format\x18\x03 \x01(\x0e2\x1e.mbzpb.Listing.Metadata.FormatR\x06format\x122\n" +
	"\x06expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06expiry\x12.\n" +
	"\x12acceptedCurrencies\x18\x05 \x03(\tR\x12acceptedCurrencies\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x12.\n" +
	"\x12escrowTimeoutHours\x18\a \x01(\rR\x12escrowTimeoutHours\x129\n" +
	"\x0fpricingCurrency\x18\t \x01(\v2\x0f.mbzpb.CurrencyR\x0fpricingCurrency\x12H\n" +
	"\frwaTradeMode\x18\n" +
	" \x01(\x0e2$.mbzpb.Listing.Metadata.RwaTradeModeR\frwaTradeMode\x128\n" +
	"\x17rwaEscrowTimeoutSeconds\x18\v \x01(\x04R\x17rwaEscrowTimeoutSeconds\x12\"\n" +
	"\frwaListingId\x18\f \x01(\x04R\frwaListingId\"s\n" +
	"\fContractType\x12\x11\n" +
	"\rPHYSICAL_GOOD\x10\x00\x12\x10\n" +
	"\fDIGITAL_GOOD\x10\x01\x12\v\n" +
	"\aSERVICE\x10\x02\x12\x0e\n" +
	"\n" +
	"CLASSIFIED\x10\x03\x12\x12\n" +
	"\x0eCRYPTOCURRENCY\x10\x04\x12\r\n" +
	"\tRWA_TOKEN\x10\x05\"+\n" +
	"\x06Format\x12\x0f\n" +
	"\vFIXED_PRICE\x10\x00\x12\x10\n" +
	"\fMARKET_PRICE\x10\x01\"O\n" +
	"\fRwaTradeMode\x12\x1a\n" +
	"\x16RWA_TRADE_MODE_INSTANT\x10\x00\x12#\n" +
	"\x1fRWA_TRADE_MODE_CONFIRM_REQUIRED\x10\x01\x1a\xde\x11\n" +
	"\x04Item\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12*\n" +
	"\x10shortDescription\x18\x03 \x01(\tR\x10shortDescription\x12&\n" +
	"\x0eprocessingTime\x18\x04 \x01(\tR\x0eprocessingTime\x12\x12\n" +
	"\x04nsfw\x18\x05 \x01(\bR\x04nsfw\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12$\n" +
	"\x06images\x18\a \x03(\v2\f.mbzpb.ImageR\x06images\x12+\n" +
	"\n" +
	"introVideo\x18\b \x01(\v2\v.mbzpb.FileR\n" +
	"introVideo\x12 \n" +
	"\vproductType\x18\t \x01(\tR\vproductType\x12\x14\n" +
	"\x05grams\x18\n" +
	" \x01(\rR\x05grams\x12>\n" +
	"\n" +
	"dimensions\x18\v \x01(\v2\x1e.mbzpb.Listing.Item.DimensionsR\n" +
	"dimensions\x12\x1c\n" +
	"\tcondition\x18\f \x01(\tR\tcondition\x124\n" +
	"\aoptions\x18\r \x03(\v2\x1a.mbzpb.Listing.Item.OptionR\aoptions\x12+\n" +
	"\x04skus\x18\x0e \x03(\v2\x17.mbzpb.Listing.Item.SkuR\x04skus\x12\x14\n" +
	"\x05price\x18\x0f \x01(\tR\x05price\x12\"\n" +
	"\fregularPrice\x18\x10 \x01(\tR\fregularPrice\x12\x1c\n" +
	"\tsalePrice\x18\x11 \x01(\tR\tsalePrice\x12O\n" +
	"\x10optionalFeatures\x18\x12 \x03(\v2#.mbzpb.Listing.Item.OptionalFeatureR\x10optionalFeatures\x12<\n" +
	"\x19cryptoListingCurrencyCode\x18\x13 \x01(\tR\x19cryptoListingCurrencyCode\x12>\n" +
	"\x1acryptoListingPriceModifier\x18\x14 \x01(\x02R\x1acryptoListingPriceModifier\x12.\n" +
	"\x12altIntroVideoLinks\x18\x15 \x03(\tR\x12altIntroVideoLinks\x12 \n" +
	"\vminQuantity\x18\x16 \x01(\tR\vminQuantity\x12 \n" +
	"\vmaxQuantity\x18\x17 \x01(\tR\vmaxQuantity\x12\x1e\n" +
	"\n" +
	"blockchain\x18\x18 \x01(\tR\n" +
	"blockchain\x12\"\n" +
	"\ftokenAddress\x18\x19 \x01(\tR\ftokenAddress\x12$\n" +
	"\rtokenStandard\x18\x1a \x01(\tR\rtokenStandard\x12\x18\n" +
	"\atokenId\x18\x1b \x01(\tR\atokenId\x12\x16\n" +
	"\x06slotId\x18\x1c \x01(\tR\x06slotId\x12\x1e\n" +
	"\n" +
	"weightUnit\x18\x1d \x01(\tR\n" +
	"weightUnit\x12(\n" +
	"\x0finventoryPolicy\x18\x1e \x01(\tR\x0finventoryPolicy\x12$\n" +
	"\rpackageLength\x18\x1f \x01(\x02R\rpackageLength\x12\"\n" +
	"\fpackageWidth\x18  \x01(\x02R\fpackageWidth\x12$\n" +
	"\rpackageHeight\x18! \x01(\x02R\rpackageHeight\x12$\n" +
	"\rdimensionUnit\x18\" \x01(\tR\rdimensionUnit\x12\x14\n" +
	"\x05brand\x18# \x01(\tR\x05brand\x1a\xc1\x01\n" +
	"\x06Option\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12>\n" +
	"\bvariants\x18\x03 \x03(\v2\".mbzpb.Listing.Item.Option.VariantR\bvariants\x1aA\n" +
	"\aVariant\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\x05image\x18\x02 \x01(\v2\f.mbzpb.ImageR\x05image\x1a\x8f\x04\n" +
	"\x03Sku\x12A\n" +
	"\n" +
	"selections\x18\x01 \x03(\v2!.mbzpb.Listing.Item.Sku.SelectionR\n" +
	"selections\x12\x1c\n" +
	"\tproductID\x18\x02 \x01(\tR\tproductID\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\tR\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12$\n" +
	"\x06images\x18\x05 \x03(\v2\f.mbzpb.ImageR\x06images\x12\"\n" +
	"\fdownloadable\x18\x06 \x01(\bR\fdownloadable\x12>\n" +
	"\tdownloads\x18\a \x03(\v2 .mbzpb.Listing.Item.Sku.DownloadR\tdownloads\x12&\n" +
	"\x0ecompareAtPrice\x18\b \x01(\tR\x0ecompareAtPrice\x12\x18\n" +
	"\abarcode\x18\t \x01(\tR\abarcode\x12\x16\n" +
	"\x06weight\x18\n" +
	" \x01(\rR\x06weight\x1a=\n" +
	"\tSelection\x12\x16\n" +
	"\x06option\x18\x01 \x01(\tR\x06option\x12\x18\n" +
	"\avariant\x18\x02 \x01(\tR\avariant\x1aR\n" +
	"\bDownload\x12\x1e\n" +
	"\n" +
	"downloadID\x18\x01 \x01(\tR\n" +
	"downloadID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x1aR\n" +
	"\n" +
	"Dimensions\x12\x16\n" +
	"\x06length\x18\x01 \x01(\rR\x06length\x12\x14\n" +
	"\x05width\x18\x02 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\rR\x06height\x1a\x7f\n" +
	"\x0fOptionalFeature\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tsurcharge\x18\x03 \x01(\tR\tsurcharge\x12\x14\n" +
	"\x05skuID\x18\x04 \x01(\tR\x05skuID\x12$\n" +
	"\x06images\x18\x05 \x03(\v2\f.mbzpb.ImageR\x06images\x1a\x81\x01\n" +
	"\x03Tax\x12\x18\n" +
	"\ataxType\x18\x01 \x01(\tR\ataxType\x12\x1e\n" +
	"\n" +
	"taxRegions\x18\x02 \x03(\tR\n" +
	"taxRegions\x12 \n" +
	"\vtaxShipping\x18\x03 \x01(\bR\vtaxShipping\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x02R\n" +
	"percentageJ\x04\b\x05\x10\x06J\x04\b\a\x10\bJ\x04\b\t\x10\n" +
	"J\x04\b\n" +
	"\x10\vR\x0fshippingOptionsR\acouponsR\x12termsAndConditionsR\frefundPolicy\"i\n" +
	"\rSignedListing\x12(\n" +
	"\alisting\x18\x01 \x01(\v2\x0e.mbzpb.ListingR\alisting\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\tR\x03cid\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xc6\x04\n" +
	"\fShippingRate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\tR\x05price\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12,\n" +
	"\x11estimatedDelivery\x18\x05 \x01(\tR\x11estimatedDelivery\x12?\n" +
	"\tcondition\x18\x06 \x01(\v2!.mbzpb.ShippingRate.RateConditionR\tcondition\x12_\n" +
	"\x15freeShippingThreshold\x18\a \x01(\v2).mbzpb.ShippingRate.FreeShippingThresholdR\x15freeShippingThreshold\x1a\xbe\x01\n" +
	"\rRateCondition\x12C\n" +
	"\x04type\x18\x01 \x01(\x0e2/.mbzpb.ShippingRate.RateCondition.ConditionTypeR\x04type\x12\x1a\n" +
	"\bminValue\x18\x02 \x01(\rR\bminValue\x12\x1a\n" +
	"\bmaxValue\x18\x03 \x01(\rR\bmaxValue\"0\n" +
	"\rConditionType\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06WEIGHT\x10\x01\x12\t\n" +
	"\x05PRICE\x10\x02\x1aO\n" +
	"\x15FreeShippingThreshold\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1c\n" +
	"\tminAmount\x18\x02 \x01(\tR\tminAmount\"w\n" +
	"\fShippingZone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aregions\x18\x03 \x03(\tR\aregions\x12)\n" +
	"\x05rates\x18\x04 \x03(\v2\x13.mbzpb.ShippingRateR\x05rates\"n\n" +
	"\x10ShippingLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1c\n" +
	"\tisDefault\x18\x04 \x01(\bR\tisDefault\"l\n" +
	"\rLocationGroup\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vlocationIds\x18\x02 \x03(\tR\vlocationIds\x12)\n" +
	"\x05zones\x18\x03 \x03(\v2\x13.mbzpb.ShippingZoneR\x05zones\"\x93\x02\n" +
	"\x0fShippingProfile\x12\x1c\n" +
	"\tprofileID\x18\x01 \x01(\tR\tprofileID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tisDefault\x18\x03 \x01(\bR\tisDefault\x12<\n" +
	"\x0elocationGroups\x18\x04 \x03(\v2\x14.mbzpb.LocationGroupR\x0elocationGroups\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\n" +
	"Z\b../mbzpbb\x06proto3"

var (
	file_listing_proto_rawDescOnce sync.Once
	file_listing_proto_rawDescData []byte
)

func file_listing_proto_rawDescGZIP() []byte {
	file_listing_proto_rawDescOnce.Do(func() {
		file_listing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)))
	})
	return file_listing_proto_rawDescData
}

var file_listing_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_listing_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_listing_proto_goTypes = []any{
	(Listing_Metadata_ContractType)(0),            // 0: mbzpb.Listing.Metadata.ContractType
	(Listing_Metadata_Format)(0),                  // 1: mbzpb.Listing.Metadata.Format
	(Listing_Metadata_RwaTradeMode)(0),            // 2: mbzpb.Listing.Metadata.RwaTradeMode
	(ShippingRate_RateCondition_ConditionType)(0), // 3: mbzpb.ShippingRate.RateCondition.ConditionType
	(*Listing)(nil),                               // 4: mbzpb.Listing
	(*SignedListing)(nil),                         // 5: mbzpb.SignedListing
	(*ShippingRate)(nil),                          // 6: mbzpb.ShippingRate
	(*ShippingZone)(nil),                          // 7: mbzpb.ShippingZone
	(*ShippingLocation)(nil),                      // 8: mbzpb.ShippingLocation
	(*LocationGroup)(nil),                         // 9: mbzpb.LocationGroup
	(*ShippingProfile)(nil),                       // 10: mbzpb.ShippingProfile
	(*Listing_Metadata)(nil),                      // 11: mbzpb.Listing.Metadata
	(*Listing_Item)(nil),                          // 12: mbzpb.Listing.Item
	(*Listing_Tax)(nil),                           // 13: mbzpb.Listing.Tax
	(*Listing_Item_Option)(nil),                   // 14: mbzpb.Listing.Item.Option
	(*Listing_Item_Sku)(nil),                      // 15: mbzpb.Listing.Item.Sku
	(*Listing_Item_Dimensions)(nil),               // 16: mbzpb.Listing.Item.Dimensions
	(*Listing_Item_OptionalFeature)(nil),          // 17: mbzpb.Listing.Item.OptionalFeature
	(*Listing_Item_Option_Variant)(nil),           // 18: mbzpb.Listing.Item.Option.Variant
	(*Listing_Item_Sku_Selection)(nil),            // 19: mbzpb.Listing.Item.Sku.Selection
	(*Listing_Item_Sku_Download)(nil),             // 20: mbzpb.Listing.Item.Sku.Download
	(*ShippingRate_RateCondition)(nil),            // 21: mbzpb.ShippingRate.RateCondition
	(*ShippingRate_FreeShippingThreshold)(nil),    // 22: mbzpb.ShippingRate.FreeShippingThreshold
	(*ID)(nil),                    // 23: mbzpb.ID
	(*timestamppb.Timestamp)(nil), // 24: google.protobuf.Timestamp
	(*Currency)(nil),              // 25: mbzpb.Currency
	(*Image)(nil),                 // 26: mbzpb.Image
	(*File)(nil),                  // 27: mbzpb.File
}
var file_listing_proto_depIdxs = []int32{
	23, // 0: mbzpb.Listing.vendorID:type_name -> mbzpb.ID
	11, // 1: mbzpb.Listing.metadata:type_name -> mbzpb.Listing.Metadata
	12, // 2: mbzpb.Listing.item:type_name -> mbzpb.Listing.Item
	13, // 3: mbzpb.Listing.taxes:type_name -> mbzpb.Listing.Tax
	10, // 4: mbzpb.Listing.shippingProfile:type_name -> mbzpb.ShippingProfile
	4,  // 5: mbzpb.SignedListing.listing:type_name -> mbzpb.Listing
	21, // 6: mbzpb.ShippingRate.condition:type_name -> mbzpb.ShippingRate.RateCondition
	22, // 7: mbzpb.ShippingRate.freeShippingThreshold:type_name -> mbzpb.ShippingRate.FreeShippingThreshold
	6,  // 8: mbzpb.ShippingZone.rates:type_name -> mbzpb.ShippingRate
	7,  // 9: mbzpb.LocationGroup.zones:type_name -> mbzpb.ShippingZone
	9,  // 10: mbzpb.ShippingProfile.locationGroups:type_name -> mbzpb.LocationGroup
	24, // 11: mbzpb.ShippingProfile.createdAt:type_name -> google.protobuf.Timestamp
	24, // 12: mbzpb.ShippingProfile.updatedAt:type_name -> google.protobuf.Timestamp
	0,  // 13: mbzpb.Listing.Metadata.contractType:type_name -> mbzpb.Listing.Metadata.ContractType
	1,  // 14: mbzpb.Listing.Metadata.format:type_name -> mbzpb.Listing.Metadata.Format
	24, // 15: mbzpb.Listing.Metadata.expiry:type_name -> google.protobuf.Timestamp
	25, // 16: mbzpb.Listing.Metadata.pricingCurrency:type_name -> mbzpb.Currency
	2,  // 17: mbzpb.Listing.Metadata.rwaTradeMode:type_name -> mbzpb.Listing.Metadata.RwaTradeMode
	26, // 18: mbzpb.Listing.Item.images:type_name -> mbzpb.Image
	27, // 19: mbzpb.Listing.Item.introVideo:type_name -> mbzpb.File
	16, // 20: mbzpb.Listing.Item.dimensions:type_name -> mbzpb.Listing.Item.Dimensions
	14, // 21: mbzpb.Listing.Item.options:type_name -> mbzpb.Listing.Item.Option
	15, // 22: mbzpb.Listing.Item.skus:type_name -> mbzpb.Listing.Item.Sku
	17, // 23: mbzpb.Listing.Item.optionalFeatures:type_name -> mbzpb.Listing.Item.OptionalFeature
	18, // 24: mbzpb.Listing.Item.Option.variants:type_name -> mbzpb.Listing.Item.Option.Variant
	19, // 25: mbzpb.Listing.Item.Sku.selections:type_name -> mbzpb.Listing.Item.Sku.Selection
	26, // 26: mbzpb.Listing.Item.Sku.images:type_name -> mbzpb.Image
	20, // 27: mbzpb.Listing.Item.Sku.downloads:type_name -> mbzpb.Listing.Item.Sku.Download
	26, // 28: mbzpb.Listing.Item.OptionalFeature.images:type_name -> mbzpb.Image
	26, // 29: mbzpb.Listing.Item.Option.Variant.image:type_name -> mbzpb.Image
	3,  // 30: mbzpb.ShippingRate.RateCondition.type:type_name -> mbzpb.ShippingRate.RateCondition.ConditionType
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_listing_proto_init() }
func file_listing_proto_init() {
	if File_listing_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listing_proto_rawDesc), len(file_listing_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listing_proto_goTypes,
		DependencyIndexes: file_listing_proto_depIdxs,
		EnumInfos:         file_listing_proto_enumTypes,
		MessageInfos:      file_listing_proto_msgTypes,
	}.Build()
	File_listing_proto = out.File
	file_listing_proto_goTypes = nil
	file_listing_proto_depIdxs = nil
}
