// Package media provides IPFS-compatible content identifier (CID) computation
// without requiring an IPFS daemon. It uses the boxo library to build UnixFS
// DAGs in memory, producing CIDs identical to those generated by `ipfs add`.
package media

import (
	"bytes"
	"fmt"

	bsrv "github.com/ipfs/boxo/blockservice"
	"github.com/ipfs/boxo/blockstore"
	chunker "github.com/ipfs/boxo/chunker"
	"github.com/ipfs/boxo/exchange/offline"
	"github.com/ipfs/boxo/ipld/merkledag"
	"github.com/ipfs/boxo/ipld/unixfs/importer/balanced"
	ihelper "github.com/ipfs/boxo/ipld/unixfs/importer/helpers"
	"github.com/ipfs/go-cid"
	ds "github.com/ipfs/go-datastore"
	dssync "github.com/ipfs/go-datastore/sync"
)

// ComputeUnixFSCID calculates the IPFS-compatible CID for data using pure
// in-memory UnixFS DAG construction. The result is identical to `ipfs add`
// with default settings:
//
//   - CIDv0 (dag-pb codec, SHA2-256 multihash)
//   - 256 KiB chunk size (chunker.DefaultBlockSize)
//   - Balanced DAG layout
//   - Non-raw leaves (data wrapped in UnixFS protobuf)
//   - DefaultLinksPerBlock (174 links per intermediate node)
//
// Performance: <1ms for typical media files vs ~100ms with IPFS daemon
// (eliminates temp file I/O, IPFS add, and unpin).
func ComputeUnixFSCID(data []byte) (cid.Cid, error) {
	mbs := blockstore.NewBlockstore(dssync.MutexWrap(ds.NewMapDatastore()))
	dsvc := merkledag.NewDAGService(bsrv.New(mbs, offline.Exchange(mbs)))

	spl, err := chunker.FromString(bytes.NewReader(data), "")
	if err != nil {
		return cid.Undef, fmt.Errorf("chunker init: %w", err)
	}

	params := ihelper.DagBuilderParams{
		Maxlinks:   ihelper.DefaultLinksPerBlock,
		RawLeaves:  false,
		CidBuilder: merkledag.V0CidPrefix(),
		Dagserv:    dsvc,
	}

	db, err := params.New(spl)
	if err != nil {
		return cid.Undef, fmt.Errorf("dag builder init: %w", err)
	}

	nd, err := balanced.Layout(db)
	if err != nil {
		return cid.Undef, fmt.Errorf("balanced layout: %w", err)
	}

	return nd.Cid(), nil
}
