import { createApp } from 'vue';
import { createStore } from 'vuex'
import App from './App.vue';
import { TUIComponents, TUICore, genTestUserSig } from './TUIKit';
// import TUICallKit
import { TUICallKit } from '@tencentcloud/call-uikit-vue';

import './assets/global.less';
import components from './components/global';
import products from './store/products.module'
import Router from './router/index';

import sifter from 'sifter';
import microplugin from 'microplugin';
import $ from "jquery";

window.jQuery = window.$ = $;
window.Sifter = sifter;
window.MicroPlugin = microplugin;

const SDKAppID = 1771000181; // Your SDKAppID
const secretKey = '340f95d79d6810703504d6b9008c901a20070905605f38ff5a49dd23811f85b6'; //Your secretKey
const userID = 'test123'; // User ID

const app = createApp(App)
app.config.productionTip = false

// components
for (const i in components) {
  app.component(i, components[i])
}

const store = createStore({
  modules: {
    products
  }
})

$.vueRouter = Router;
$.vueStore = store;

// init TUIKit
const TUIKit = TUICore.init({
  SDKAppID,
});
// TUIKit add TUIComponents
TUIKit.use(TUIComponents);
// TUIKit add TUICallKit
TUIKit.use(TUICallKit);

// login TUIKit
TUIKit.login({
  userID: userID,
  userSig: genTestUserSig({
    SDKAppID,
    secretKey,
    userID,
  }).userSig, // The password with which the user logs in to IM. It is the ciphertext generated by encrypting information such as userID.For the detailed generation method, see Generating UserSig
});

app.use(Router).use(TUIKit).use(store).mount('#app')
