// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: msg.proto

package mbzpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_MessageType int32

const (
	Message_ACK              Message_MessageType = 0
	Message_PING             Message_MessageType = 1
	Message_PONG             Message_MessageType = 2
	Message_FOLLOW           Message_MessageType = 4
	Message_UNFOLLOW         Message_MessageType = 5
	Message_STORE            Message_MessageType = 6
	Message_ORDER            Message_MessageType = 7
	Message_DISPUTE          Message_MessageType = 8
	Message_ADDRESS_REQUEST  Message_MessageType = 9
	Message_ADDRESS_RESPONSE Message_MessageType = 10
)

// Enum value maps for Message_MessageType.
var (
	Message_MessageType_name = map[int32]string{
		0:  "ACK",
		1:  "PING",
		2:  "PONG",
		4:  "FOLLOW",
		5:  "UNFOLLOW",
		6:  "STORE",
		7:  "ORDER",
		8:  "DISPUTE",
		9:  "ADDRESS_REQUEST",
		10: "ADDRESS_RESPONSE",
	}
	Message_MessageType_value = map[string]int32{
		"ACK":              0,
		"PING":             1,
		"PONG":             2,
		"FOLLOW":           4,
		"UNFOLLOW":         5,
		"STORE":            6,
		"ORDER":            7,
		"DISPUTE":          8,
		"ADDRESS_REQUEST":  9,
		"ADDRESS_RESPONSE": 10,
	}
)

func (x Message_MessageType) Enum() *Message_MessageType {
	p := new(Message_MessageType)
	*p = x
	return p
}

func (x Message_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (Message_MessageType) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x Message_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_MessageType.Descriptor instead.
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0, 0}
}

type OrderMessage_MessageType int32

const (
	OrderMessage_ORDER_OPEN              OrderMessage_MessageType = 0
	OrderMessage_ORDER_DECLINE           OrderMessage_MessageType = 1
	OrderMessage_ORDER_CANCEL            OrderMessage_MessageType = 2
	OrderMessage_ORDER_CONFIRMATION      OrderMessage_MessageType = 3
	OrderMessage_RATING_SIGNATURES       OrderMessage_MessageType = 4
	OrderMessage_ORDER_FULFILLMENT       OrderMessage_MessageType = 5
	OrderMessage_ORDER_COMPLETE          OrderMessage_MessageType = 6
	OrderMessage_DISPUTE_OPEN            OrderMessage_MessageType = 7
	OrderMessage_DISPUTE_UPDATE          OrderMessage_MessageType = 8
	OrderMessage_DISPUTE_CLOSE           OrderMessage_MessageType = 9
	OrderMessage_DISPUTE_ACCEPT          OrderMessage_MessageType = 10
	OrderMessage_REFUND                  OrderMessage_MessageType = 11
	OrderMessage_PAYMENT_SENT            OrderMessage_MessageType = 12
	OrderMessage_PAYMENT_FINALIZED       OrderMessage_MessageType = 13
	OrderMessage_PAYMENT_LOCKED          OrderMessage_MessageType = 14 // RWA 确认交易模式资金锁定
	OrderMessage_AFTER_SALE_DISPUTE_OPEN OrderMessage_MessageType = 15
)

// Enum value maps for OrderMessage_MessageType.
var (
	OrderMessage_MessageType_name = map[int32]string{
		0:  "ORDER_OPEN",
		1:  "ORDER_DECLINE",
		2:  "ORDER_CANCEL",
		3:  "ORDER_CONFIRMATION",
		4:  "RATING_SIGNATURES",
		5:  "ORDER_FULFILLMENT",
		6:  "ORDER_COMPLETE",
		7:  "DISPUTE_OPEN",
		8:  "DISPUTE_UPDATE",
		9:  "DISPUTE_CLOSE",
		10: "DISPUTE_ACCEPT",
		11: "REFUND",
		12: "PAYMENT_SENT",
		13: "PAYMENT_FINALIZED",
		14: "PAYMENT_LOCKED",
		15: "AFTER_SALE_DISPUTE_OPEN",
	}
	OrderMessage_MessageType_value = map[string]int32{
		"ORDER_OPEN":              0,
		"ORDER_DECLINE":           1,
		"ORDER_CANCEL":            2,
		"ORDER_CONFIRMATION":      3,
		"RATING_SIGNATURES":       4,
		"ORDER_FULFILLMENT":       5,
		"ORDER_COMPLETE":          6,
		"DISPUTE_OPEN":            7,
		"DISPUTE_UPDATE":          8,
		"DISPUTE_CLOSE":           9,
		"DISPUTE_ACCEPT":          10,
		"REFUND":                  11,
		"PAYMENT_SENT":            12,
		"PAYMENT_FINALIZED":       13,
		"PAYMENT_LOCKED":          14,
		"AFTER_SALE_DISPUTE_OPEN": 15,
	}
)

func (x OrderMessage_MessageType) Enum() *OrderMessage_MessageType {
	p := new(OrderMessage_MessageType)
	*p = x
	return p
}

func (x OrderMessage_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderMessage_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[1].Descriptor()
}

func (OrderMessage_MessageType) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[1]
}

func (x OrderMessage_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderMessage_MessageType.Descriptor instead.
func (OrderMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3, 0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   Message_MessageType    `protobuf:"varint,1,opt,name=messageType,proto3,enum=mbzpb.Message_MessageType" json:"messageType,omitempty"`
	MessageID     string                 `protobuf:"bytes,2,opt,name=messageID,proto3" json:"messageID,omitempty"`
	Sequence      uint32                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessageType() Message_MessageType {
	if x != nil {
		return x.MessageType
	}
	return Message_ACK
}

func (x *Message) GetMessageID() string {
	if x != nil {
		return x.MessageID
	}
	return ""
}

func (x *Message) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Message) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StoreMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cids          [][]byte               `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreMessage) Reset() {
	*x = StoreMessage{}
	mi := &file_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMessage) ProtoMessage() {}

func (x *StoreMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMessage.ProtoReflect.Descriptor instead.
func (*StoreMessage) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *StoreMessage) GetCids() [][]byte {
	if x != nil {
		return x.Cids
	}
	return nil
}

type AckMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AckedMessageID string                 `protobuf:"bytes,1,opt,name=ackedMessageID,proto3" json:"ackedMessageID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AckMessage) Reset() {
	*x = AckMessage{}
	mi := &file_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMessage) ProtoMessage() {}

func (x *AckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMessage.ProtoReflect.Descriptor instead.
func (*AckMessage) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *AckMessage) GetAckedMessageID() string {
	if x != nil {
		return x.AckedMessageID
	}
	return ""
}

type OrderMessage struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	OrderID       string                   `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	MessageType   OrderMessage_MessageType `protobuf:"varint,2,opt,name=messageType,proto3,enum=mbzpb.OrderMessage_MessageType" json:"messageType,omitempty"`
	Message       *anypb.Any               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                   `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	SenderPeerID  string                   `protobuf:"bytes,5,opt,name=senderPeerID,proto3" json:"senderPeerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderMessage) Reset() {
	*x = OrderMessage{}
	mi := &file_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMessage) ProtoMessage() {}

func (x *OrderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMessage.ProtoReflect.Descriptor instead.
func (*OrderMessage) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *OrderMessage) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *OrderMessage) GetMessageType() OrderMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return OrderMessage_ORDER_OPEN
}

func (x *OrderMessage) GetMessage() *anypb.Any {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *OrderMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *OrderMessage) GetSenderPeerID() string {
	if x != nil {
		return x.SenderPeerID
	}
	return ""
}

type AfterSaleDisputeOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AfterSaleDisputeOpen) Reset() {
	*x = AfterSaleDisputeOpen{}
	mi := &file_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AfterSaleDisputeOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AfterSaleDisputeOpen) ProtoMessage() {}

func (x *AfterSaleDisputeOpen) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AfterSaleDisputeOpen.ProtoReflect.Descriptor instead.
func (*AfterSaleDisputeOpen) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *AfterSaleDisputeOpen) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *AfterSaleDisputeOpen) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AfterSaleDisputeOpen) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AfterSaleDisputeOpen) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type OrderList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*OrderMessage        `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderList) Reset() {
	*x = OrderList{}
	mi := &file_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderList) ProtoMessage() {}

func (x *OrderList) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderList.ProtoReflect.Descriptor instead.
func (*OrderList) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{5}
}

func (x *OrderList) GetMessages() []*OrderMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AddressRequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coin          string                 `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressRequestMessage) Reset() {
	*x = AddressRequestMessage{}
	mi := &file_msg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressRequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressRequestMessage) ProtoMessage() {}

func (x *AddressRequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressRequestMessage.ProtoReflect.Descriptor instead.
func (*AddressRequestMessage) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{6}
}

func (x *AddressRequestMessage) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

type AddressResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Coin          string                 `protobuf:"bytes,2,opt,name=coin,proto3" json:"coin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressResponseMessage) Reset() {
	*x = AddressResponseMessage{}
	mi := &file_msg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponseMessage) ProtoMessage() {}

func (x *AddressResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponseMessage.ProtoReflect.Descriptor instead.
func (*AddressResponseMessage) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{7}
}

func (x *AddressResponseMessage) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressResponseMessage) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderPubkey  []byte                 `protobuf:"bytes,1,opt,name=senderPubkey,proto3" json:"senderPubkey,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_msg_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{8}
}

func (x *Envelope) GetSenderPubkey() []byte {
	if x != nil {
		return x.SenderPubkey
	}
	return nil
}

func (x *Envelope) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_msg_proto protoreflect.FileDescriptor

const file_msg_proto_rawDesc = "" +
	"\n" +
	"\tmsg.proto\x12\x05mbzpb\x1a\x19google/protobuf/any.proto\"\xc6\x02\n" +
	"\aMessage\x12<\n" +
	"\vmessageType\x18\x01 \x01(\x0e2\x1a.mbzpb.Message.MessageTypeR\vmessageType\x12\x1c\n" +
	"\tmessageID\x18\x02 \x01(\tR\tmessageID\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\rR\bsequence\x12.\n" +
	"\apayload\x18\x04 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x92\x01\n" +
	"\vMessageType\x12\a\n" +
	"\x03ACK\x10\x00\x12\b\n" +
	"\x04PING\x10\x01\x12\b\n" +
	"\x04PONG\x10\x02\x12\n" +
	"\n" +
	"\x06FOLLOW\x10\x04\x12\f\n" +
	"\bUNFOLLOW\x10\x05\x12\t\n" +
	"\x05STORE\x10\x06\x12\t\n" +
	"\x05ORDER\x10\a\x12\v\n" +
	"\aDISPUTE\x10\b\x12\x13\n" +
	"\x0fADDRESS_REQUEST\x10\t\x12\x14\n" +
	"\x10ADDRESS_RESPONSE\x10\n" +
	"\"\"\n" +
	"\fStoreMessage\x12\x12\n" +
	"\x04cids\x18\x01 \x03(\fR\x04cids\"4\n" +
	"\n" +
	"AckMessage\x12&\n" +
	"\x0eackedMessageID\x18\x01 \x01(\tR\x0eackedMessageID\"\xaf\x04\n" +
	"\fOrderMessage\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12A\n" +
	"\vmessageType\x18\x02 \x01(\x0e2\x1f.mbzpb.OrderMessage.MessageTypeR\vmessageType\x12.\n" +
	"\amessage\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\amessage\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12\"\n" +
	"\fsenderPeerID\x18\x05 \x01(\tR\fsenderPeerID\"\xcf\x02\n" +
	"\vMessageType\x12\x0e\n" +
	"\n" +
	"ORDER_OPEN\x10\x00\x12\x11\n" +
	"\rORDER_DECLINE\x10\x01\x12\x10\n" +
	"\fORDER_CANCEL\x10\x02\x12\x16\n" +
	"\x12ORDER_CONFIRMATION\x10\x03\x12\x15\n" +
	"\x11RATING_SIGNATURES\x10\x04\x12\x15\n" +
	"\x11ORDER_FULFILLMENT\x10\x05\x12\x12\n" +
	"\x0eORDER_COMPLETE\x10\x06\x12\x10\n" +
	"\fDISPUTE_OPEN\x10\a\x12\x12\n" +
	"\x0eDISPUTE_UPDATE\x10\b\x12\x11\n" +
	"\rDISPUTE_CLOSE\x10\t\x12\x12\n" +
	"\x0eDISPUTE_ACCEPT\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06REFUND\x10\v\x12\x10\n" +
	"\fPAYMENT_SENT\x10\f\x12\x15\n" +
	"\x11PAYMENT_FINALIZED\x10\r\x12\x12\n" +
	"\x0ePAYMENT_LOCKED\x10\x0e\x12\x1b\n" +
	"\x17AFTER_SALE_DISPUTE_OPEN\x10\x0f\"\x88\x01\n" +
	"\x14AfterSaleDisputeOpen\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\"<\n" +
	"\tOrderList\x12/\n" +
	"\bmessages\x18\x01 \x03(\v2\x13.mbzpb.OrderMessageR\bmessages\"+\n" +
	"\x15AddressRequestMessage\x12\x12\n" +
	"\x04coin\x18\x01 \x01(\tR\x04coin\"F\n" +
	"\x16AddressResponseMessage\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x12\n" +
	"\x04coin\x18\x02 \x01(\tR\x04coin\"v\n" +
	"\bEnvelope\x12\"\n" +
	"\fsenderPubkey\x18\x01 \x01(\fR\fsenderPubkey\x12(\n" +
	"\amessage\x18\x02 \x01(\v2\x0e.mbzpb.MessageR\amessage\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignatureB\n" +
	"Z\b../mbzpbb\x06proto3"

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData []byte
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)))
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_msg_proto_goTypes = []any{
	(Message_MessageType)(0),       // 0: mbzpb.Message.MessageType
	(OrderMessage_MessageType)(0),  // 1: mbzpb.OrderMessage.MessageType
	(*Message)(nil),                // 2: mbzpb.Message
	(*StoreMessage)(nil),           // 3: mbzpb.StoreMessage
	(*AckMessage)(nil),             // 4: mbzpb.AckMessage
	(*OrderMessage)(nil),           // 5: mbzpb.OrderMessage
	(*AfterSaleDisputeOpen)(nil),   // 6: mbzpb.AfterSaleDisputeOpen
	(*OrderList)(nil),              // 7: mbzpb.OrderList
	(*AddressRequestMessage)(nil),  // 8: mbzpb.AddressRequestMessage
	(*AddressResponseMessage)(nil), // 9: mbzpb.AddressResponseMessage
	(*Envelope)(nil),               // 10: mbzpb.Envelope
	(*anypb.Any)(nil),              // 11: google.protobuf.Any
}
var file_msg_proto_depIdxs = []int32{
	0,  // 0: mbzpb.Message.messageType:type_name -> mbzpb.Message.MessageType
	11, // 1: mbzpb.Message.payload:type_name -> google.protobuf.Any
	1,  // 2: mbzpb.OrderMessage.messageType:type_name -> mbzpb.OrderMessage.MessageType
	11, // 3: mbzpb.OrderMessage.message:type_name -> google.protobuf.Any
	5,  // 4: mbzpb.OrderList.messages:type_name -> mbzpb.OrderMessage
	2,  // 5: mbzpb.Envelope.message:type_name -> mbzpb.Message
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
