#!/bin/sh
exec 2>&1

NODE_PORT="${NODE_PORT:-5102}"

ARGS="start -d /data --gatewayaddr=/ip4/127.0.0.1/tcp/${NODE_PORT}"

if [ "$TESTNET" = "true" ] || [ "$TESTNET" = "1" ]; then
  ARGS="$ARGS --testnet"
fi

if [ -n "$SAAS_PEER_ID" ]; then
  ARGS="$ARGS --httpproxytrustedpeer=$SAAS_PEER_ID"
fi

if [ -n "$SAAS_API_URL" ]; then
  ARGS="$ARGS --saasapiurl=$SAAS_API_URL"
fi

exec /usr/local/bin/mobazha $ARGS
