#!/bin/sh
exec 2>&1

NODE_PORT="${NODE_PORT:-5102}"

ARGS="start -d /data --gatewayaddr=/ip4/127.0.0.1/tcp/${NODE_PORT}"

if [ "$TESTNET" = "true" ] || [ "$TESTNET" = "1" ]; then
  ARGS="$ARGS --testnet"
fi

if [ -n "$SAAS_PEER_ID" ]; then
  ARGS="$ARGS --httpproxytrustedpeer=$SAAS_PEER_ID"
fi

if [ -n "$SAAS_API_URL" ]; then
  ARGS="$ARGS --saasapiurl=$SAAS_API_URL"
fi

# Advertise the public HTTPS origin to Hosting so Peer-routed marketplace
# requests can reach this standalone node without relying on libp2p reachability.
if [ -n "$STORE_DOMAIN" ]; then
  case "$STORE_DOMAIN" in
    http://*|https://*) STANDALONE_ENDPOINT_URL="$STORE_DOMAIN" ;;
    *) STANDALONE_ENDPOINT_URL="https://$STORE_DOMAIN" ;;
  esac
  ARGS="$ARGS --standaloneendpointurl=$STANDALONE_ENDPOINT_URL"
fi

exec /usr/local/bin/mobazha $ARGS
